spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: "111111111111-a1aaa99aaa11a1aaaaaaaaa1aaa1a1aa.apps.googleusercontent.com"
            client-secret: "AAAAAA-aAAAaA1AAaAaaaaAAA_a11A1AAAa"
            scope:
              - profile
              - email